$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'SmartExpense.Excel.psm1') -Force -DisableNameChecking
$testOneDriveRoot=if($env:SMART_EXPENSE_TEST_ONEDRIVE_ROOT){Get-HermesOneDriveRoot -ExplicitRoot $env:SMART_EXPENSE_TEST_ONEDRIVE_ROOT}else{Get-HermesOneDriveRoot}
$script:SourceWorkbook=Join-Path $testOneDriveRoot 'Documents\2_Others\Expenses_finance\Canada plan.xlsx'
if(-not (Test-Path -LiteralPath $script:SourceWorkbook -PathType Leaf)){throw "Required source workbook was not found below the resolved OneDrive root: $script:SourceWorkbook"}

$passed = 0
function Assert-Equal([object]$Actual,[object]$Expected,[string]$Message) { if ($Actual -cne $Expected) { throw "$Message Expected=[$Expected] Actual=[$Actual]" }; $script:passed++ }
function Assert-True([bool]$Condition,[string]$Message) { if (-not $Condition) { throw $Message }; $script:passed++ }
function Assert-Throws([scriptblock]$Action,[string]$Message) { $thrown=$false;try{&$Action}catch{$thrown=$true};if(-not $thrown){throw $Message};$script:passed++ }
function New-TestRoot { $path=Join-Path ([IO.Path]::GetTempPath()) ('smart-expense-test-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force -Path $path|Out-Null;return $path }
function Write-TestJson([string]$Path,[object]$Payload) { $Payload|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $Path -Encoding utf8 }
function New-TestPayload([string]$Id,[string]$CreatedAt,[string]$ReceiptDate,[string]$Merchant,[decimal]$Amount,[string]$Currency='CAD') {
    $guid=[guid]$Id;$stamp=[datetimeoffset]$CreatedAt;$short=$guid.ToString('N').Substring(0,8).ToLowerInvariant()
    return [pscustomobject]@{schemaVersion=2;expenseId=$guid.ToString();createdAt=$CreatedAt;sourceDeviceId='test-phone';receiptDate=$ReceiptDate;merchantName=$Merchant;totalAmount=$Amount;currency=$Currency;extractionStatus='confirmed';receiptImageRelativePath=("Documents/2_Others/Expenses_finance/receipt_images/{0}/{1}_receipt_{2}.jpg" -f $stamp.ToString('yyyy-MM'),$stamp.ToString('yyyyMMdd_HHmmss'),$short)}
}
function Add-TestHandoff([string]$Root,[object]$Payload,[string]$TimestampForFile) {
    $expense=Join-Path $Root 'Documents\2_Others\Expenses_finance';$inbox=Join-Path $expense 'logs';$month=$Payload.receiptImageRelativePath.Split('/')[5];$image=Join-Path $Root ($Payload.receiptImageRelativePath -replace '/', '\');New-Item -ItemType Directory -Force -Path $inbox,(Split-Path -Parent $image)|Out-Null;New-Item -ItemType File -Force -Path $image|Out-Null;$short=([guid]$Payload.expenseId).ToString('N').Substring(0,8).ToLowerInvariant();$file="expense_${TimestampForFile}_$short.json";$path=Join-Path $inbox $file;Write-TestJson $path $Payload;return $path
}
function Copy-DisposableWorkbook([string]$Root) {
    $expense=Join-Path $Root 'Documents\2_Others\Expenses_finance';New-Item -ItemType Directory -Force -Path (Join-Path $expense 'logs')|Out-Null;Copy-Item -LiteralPath $script:SourceWorkbook -Destination (Join-Path $expense 'Canada plan.xlsx');return (Join-Path $expense 'Canada plan.xlsx')
}
function Set-WorkbookSentinel([string]$WorkbookPath) {
    $excel=$null;$book=$null;try{
        $excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$book=$excel.Workbooks.Open($WorkbookPath,$null,$false);$sheet=$book.Worksheets.Item('2026-09')
        $partialRow=$null;$targetRow=$null
        for($row=12;$row -le 99;$row++){
            $currentFree=[string]::IsNullOrWhiteSpace([string]$sheet.Cells.Item($row,6).Value2) -and [string]::IsNullOrWhiteSpace([string]$sheet.Cells.Item($row,7).Value2)
            $nextFree=[string]::IsNullOrWhiteSpace([string]$sheet.Cells.Item($row+1,6).Value2) -and [string]::IsNullOrWhiteSpace([string]$sheet.Cells.Item($row+1,7).Value2)
            if($currentFree -and $nextFree){$partialRow=$row;$targetRow=$row+1;break}
        }
        if($null -eq $partialRow){throw 'No adjacent safe transaction rows available for the structural-warning canary.'}
        $sheet.Cells.Item($partialRow,6).Value2=[double]9;$sheet.Cells.Item($targetRow,5).Value2=[double]0.5;$sheet.Cells.Item($targetRow,16).Value2='sentinel-unrelated';$book.Save();return $targetRow
    }finally{if($book){$book.Close($false);[Runtime.InteropServices.Marshal]::ReleaseComObject($book)|Out-Null};if($excel){$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}
}function Remove-DisposableSheet([string]$WorkbookPath,[string]$Name) {
    $excel=$null;$book=$null;try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false;$book=$excel.Workbooks.Open($WorkbookPath,$null,$false);$book.Worksheets.Item($Name).Delete();$book.Save()}finally{if($book){$book.Close($false);[Runtime.InteropServices.Marshal]::ReleaseComObject($book)|Out-Null};if($excel){$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}}
function Get-SummaryUsedRowCount([string]$WorkbookPath) {
    $excel=$null;$book=$null;try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$book=$excel.Workbooks.Open($WorkbookPath,$null,$true);return [int]$book.Worksheets.Item('Food Expense Summary').UsedRange.Rows.Count}finally{if($book){$book.Close($false);[Runtime.InteropServices.Marshal]::ReleaseComObject($book)|Out-Null};if($excel){$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}}
# Discovery, resolver, normalization, mapping, and conservative date parsing.
$root=New-TestRoot;$consumer=Join-Path $root 'consumer';$generic=Join-Path $root 'generic';$registry=Join-Path $root 'registry';New-Item -ItemType Directory -Force -Path $consumer,$generic,$registry|Out-Null
Assert-Equal (Get-HermesOneDriveRoot -ConsumerRoot $consumer -GenericRoot (Join-Path $root 'missing-generic') -RegistryRoots @($registry)) ([IO.Path]::GetFullPath($consumer)) 'OneDriveConsumer precedence failed.'
Assert-Throws { Get-HermesOneDriveRoot -ConsumerRoot $consumer -GenericRoot $generic } 'Conflicting environment roots were accepted.'
Assert-Equal (Get-HermesOneDriveRoot -ConsumerRoot $null -GenericRoot $null -RegistryRoots @($registry)) ([IO.Path]::GetFullPath($registry)) 'Registry fallback failed.'
Assert-Throws { Get-HermesOneDriveRoot -ConsumerRoot $null -GenericRoot $null -RegistryRoots @((Join-Path $root 'missing')) -RegistryPaths @() } 'Missing root was not rejected.'
New-Item -ItemType Directory -Force -Path (Join-Path $root 'inbox\receipt_jsons_done')|Out-Null;New-Item -ItemType File -Force -Path (Join-Path $root 'inbox\expense_20260101_010101_aaaaaaaa.json')|Out-Null;New-Item -ItemType File -Force -Path (Join-Path $root 'inbox\expense_20260101_010100_bbbbbbbb.json.uploading')|Out-Null;New-Item -ItemType File -Force -Path (Join-Path $root 'inbox\other.json')|Out-Null
$files=@(Get-HermesOrdinalFiles (Join-Path $root 'inbox'));Assert-Equal $files.Count 1 'Discovery did not filter direct final handoffs.';Assert-Equal $files[0].Name 'expense_20260101_010101_aaaaaaaa.json' 'Ordinal discovery order/filter failed.';Assert-True (-not (Test-HermesHandoffFileName 'expense_20260101_010101_AAAAAAAA.json')) 'Uppercase filename was accepted.'
Assert-Equal (Normalize-HermesMerchant ' CAFÉ,   Supermarket! ') 'café mart' 'Merchant comparison normalization failed.';Assert-Equal (Format-HermesMerchantDescription ' Example   Supermarket ' '2026-09-05') 'Example Mart Sep 05' 'Merchant display formatting failed.'
Assert-Equal (Get-HermesLegacyReceiptDate '2026-09' 'Example Mart Sep 05').ToString('yyyy-MM-dd') '2026-09-05' 'Legacy date parser failed.';Assert-True ($null -eq (Get-HermesLegacyReceiptDate '2026-09' 'Example Sep 05 and Oct 01')) 'Ambiguous legacy date was guessed.';Assert-True ($null -eq (Get-HermesLegacyReceiptDate '2026-09' 'Example Aug 05')) 'Wrong-month legacy date was accepted.'
$safe=Find-HermesSafeTransactionRow @(@{F=1;G=$null},@{F=$null;G='occupied'},@{F=$null;G=$null}) 12;Assert-Equal $safe.Row 14 'Safe row selection failed.';Assert-Equal $safe.Warnings.Count 2 'Partial row warnings failed.';Assert-True (-not (Find-HermesSafeTransactionRow (@(1..89|ForEach-Object {@{F=$_;G="x$_"}})) 12).HasCapacity) 'Full transaction capacity was not detected.'

# Version 2 validation and duplicate classification.
$payload=New-TestPayload 'aaaaaaaa-1111-4111-8111-111111111111' '2026-09-05T12:34:56-07:00' '2026-09-05' 'Example Supermarket' 42.35;$validPath=Add-TestHandoff $root $payload '20260905_123456';$valid=Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root;Assert-True $valid.Valid 'Valid Version 2 handoff failed.';Assert-Equal $valid.Description 'Example Mart Sep 05' 'Validated description mapping failed.'
$payload.schemaVersion='2';Assert-Equal (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root).ReasonCode 'invalid_schema_type' 'String schemaVersion was accepted.';$payload.schemaVersion=2
$payload.totalAmount='42.35';Assert-Equal (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root).ReasonCode 'invalid_amount' 'String totalAmount was accepted.';$payload.totalAmount=[decimal]42.35
$payload.createdAt='09/05/2026 12:34:56-07:00';Assert-Equal (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root).ReasonCode 'invalid_created_at' 'Non-ISO createdAt was accepted.';$payload.createdAt='2026-09-05T12:34:56-07:00'
$payload.receiptImageRelativePath=$payload.receiptImageRelativePath.Replace('/','\');Assert-Equal (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root).ReasonCode 'invalid_image_path' 'Backslash image path was accepted.';$payload.receiptImageRelativePath=$payload.receiptImageRelativePath.Replace('\','/')
$payload|Add-Member -NotePropertyName taxAmount -NotePropertyValue '1.25';Assert-Equal (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root).ReasonCode 'invalid_tax_amount' 'String taxAmount was accepted.';$payload.taxAmount=[decimal]1.25
$payload|Add-Member -NotePropertyName category -NotePropertyValue 123;Assert-Equal (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root).ReasonCode 'invalid_optional_field' 'Non-string optional category was accepted.';$payload.category='Grocery'
$payload.receiptImageRelativePath='../escape.jpg';Assert-True (-not (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $validPath) $root).Valid) 'Traversal image path was accepted.';$payload=New-TestPayload 'bbbbbbbb-2222-4222-8222-222222222222' '2026-09-05T12:34:56-07:00' '2026-09-05' 'Example Shop' 42.35;$payload.extractionStatus='low_confidence';$badStatusPath=Add-TestHandoff $root $payload '20260905_123457';Assert-Equal (Test-HermesVersion2Handoff $payload (Split-Path -Leaf $badStatusPath) $root).ReasonCode 'invalid_status' 'Disallowed status was accepted.';$payload=New-TestPayload 'cccccccc-3333-4333-8333-333333333333' '2026-09-05T12:34:56-07:00' '2026-09-05' 'Example Shop' 42.35;$payload.currency='USD';$nonCadPath=Add-TestHandoff $root $payload '20260905_123458';$v=Test-HermesVersion2Handoff $payload (Split-Path -Leaf $nonCadPath) $root;Assert-True $v.Valid 'Valid non-CAD handoff was rejected before review.'
$record=[pscustomobject]@{ReceiptDate=[datetime]'2026-09-05';Amount=42.35;NormalizedMerchant=(Normalize-HermesMerchant 'Example Supermarket');Sheet='2026-09';Row=30};$exact=Get-HermesDuplicateDecision ([pscustomobject]@{ReceiptDate=[datetime]'2026-09-05';Amount=42.350;NormalizedMerchant='example mart'}) @($record);Assert-Equal $exact.Outcome 'exact_duplicate' 'Exact duplicate classification failed.';$similar=Get-HermesDuplicateDecision ([pscustomobject]@{ReceiptDate=[datetime]'2026-09-05';Amount=42.35;NormalizedMerchant='other merchant'}) @($record);Assert-Equal $similar.Outcome 'review' 'Same-date/amount review classification failed.';$distinct=Get-HermesDuplicateDecision ([pscustomobject]@{ReceiptDate=[datetime]'2026-09-06';Amount=42.35;NormalizedMerchant='other merchant'}) @($record);Assert-Equal $distinct.Outcome 'inserted' 'Distinct record classification failed.'

# Atomic state, routing, sidecars, and processor recovery seams.
$statePath=Join-Path $root 'state.json';$state=[ordered]@{schemaVersion=1;records=[ordered]@{}};Write-HermesState $state $statePath;Assert-Equal (Read-HermesState $statePath).schemaVersion 1 'Atomic state round trip failed.';$corruptStatePath=Join-Path $root 'corrupt-state.json';Write-TestJson $corruptStatePath ([ordered]@{schemaVersion=1;records=[ordered]@{'aaaaaaaa-1111-4111-8111-111111111111'=[ordered]@{outcome='bogus'}}});Assert-Throws {Read-HermesState $corruptStatePath|Out-Null} 'Malformed state record falsely proved completion.';Write-TestJson $corruptStatePath ([ordered]@{schemaVersion='1';records=[ordered]@{}});Assert-Throws {Read-HermesState $corruptStatePath|Out-Null} 'String state schemaVersion was accepted.';$review=Join-Path $root 'review';$sidecar=Write-HermesSidecar $review 'example.json' 'review' 'non_cad' 'Only CAD.' @([pscustomobject]@{sheet='2026-09';row=12});Assert-True (Test-Path $sidecar) 'Review sidecar was not written.';Assert-True (-not ((Get-Content -Raw $sidecar) -match 'merchantName|totalAmount')) 'Sidecar leaked payload fields.'
$routeRoot=New-TestRoot;$routeSource=Join-Path $routeRoot 'expense_20260905_123456_aaaaaaaa.json';Set-Content -LiteralPath $routeSource -Value '{}';Assert-Throws {Move-HermesHandoffWithSidecar -SourcePath $routeSource -DestinationFolder (Join-Path $routeRoot 'review') -Outcome review -ReasonCode test -Message test -SidecarWriter {throw 'injected_sidecar_failure'}|Out-Null} 'Injected sidecar failure did not fail routing.';Assert-True (Test-Path $routeSource) 'Sidecar failure did not roll the handoff back to the inbox.';Assert-True (-not (Test-Path (Join-Path $routeRoot 'review\expense_20260905_123456_aaaaaaaa.json'))) 'Sidecar failure stranded the handoff in a non-recursed folder.'
$sidecarFailure=New-TestRoot;$sidecarPayload=New-TestPayload '20202020-7777-4777-8777-777777777777' '2026-09-15T12:00:00-07:00' '2026-09-15' 'Sidecar Shop' 14.5 'USD';$sidecarPath=Add-TestHandoff $sidecarFailure $sidecarPayload '20260915_120000';$sidecarRun=Invoke-HermesProcessor -OneDriveRoot $sidecarFailure -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/missing.xlsx' -StatePath (Join-Path $sidecarFailure 'state.json') -LogPath (Join-Path $sidecarFailure 'processor.jsonl') -SidecarWriter {throw 'injected_sidecar_failure'};Assert-Equal $sidecarRun.items.Count 1 'Sidecar routing failure produced duplicate result items.';Assert-Equal $sidecarRun.counts.review 0 'Sidecar routing failure was also counted as review.';Assert-Equal $sidecarRun.counts.failed 1 'Sidecar routing failure was not counted as failed.';Assert-True (Test-Path $sidecarPath) 'Processor sidecar failure did not leave the handoff retryable.'
$fake={param($workbook,$items,$dry) [pscustomobject]@{Saved=$true;Items=@($items|ForEach-Object {[pscustomobject]@{FileName=$_.FileName;ExpenseId=$_.Validation.ExpenseId;Outcome='inserted';ReasonCode='inserted';Message='fake insert';Sheet=$_.Validation.ReceiptMonth;Row=12;Candidates=@()}})}};$proc=Invoke-HermesProcessor -OneDriveRoot $root -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath $statePath -LogPath (Join-Path $root 'processor.jsonl') -WorkbookUpdater $fake;Assert-Equal $proc.counts.inserted 1 'Processor did not route fake insert.';Assert-True (Test-Path (Join-Path $root 'Documents/2_Others/Expenses_finance/logs/receipt_jsons_done')) 'Done archive was not created.';Assert-True (Test-Path (Join-Path $root 'processor.jsonl')) 'JSONL log was not written.'
$failureRoot=New-TestRoot;$failurePayload=New-TestPayload 'dddddddd-4444-4444-8444-444444444444' '2026-09-05T12:34:56-07:00' '2026-09-05' 'Failure Shop' 10;$failurePath=Add-TestHandoff $failureRoot $failurePayload '20260905_123457';$failState=Join-Path $failureRoot 'state.json';$failWriter={param($s,$p) throw 'injected_state_failure'};$failUpdate={param($w,$i,$d) [pscustomobject]@{Saved=$true;Items=@([pscustomobject]@{FileName=(Split-Path -Leaf $failurePath);ExpenseId=$failurePayload.expenseId;Outcome='inserted';ReasonCode='inserted';Message='fake';Sheet='2026-09';Row=12;Candidates=@()})}};$failedRun=Invoke-HermesProcessor -OneDriveRoot $failureRoot -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath $failState -LogPath (Join-Path $failureRoot 'log.jsonl') -WorkbookUpdater $failUpdate -StateWriter $failWriter;Assert-Equal $failedRun.counts.failed 1 'State failure was not surfaced.';Assert-True (Test-Path $failurePath) 'State failure incorrectly removed the handoff.'

# A real overlapping process lock is reported and logged instead of being silent.
$lockRoot=New-TestRoot;$lockInbox=Join-Path $lockRoot 'Documents\2_Others\Expenses_finance\logs';New-Item -ItemType Directory -Force -Path $lockInbox|Out-Null;$lockReady=Join-Path $lockRoot 'ready';$lockJob=Start-Job -ArgumentList $lockReady -ScriptBlock {param($ready)$mutex=[Threading.Mutex]::new($false,'Global\SmartExpenseTracking.HermesExcelUpdate');try{if(-not $mutex.WaitOne(0)){throw 'lock unavailable'};Set-Content -LiteralPath $ready -Value ready;Start-Sleep -Seconds 30}finally{try{$mutex.ReleaseMutex()}catch{};$mutex.Dispose()}};try{for($i=0;$i -lt 100 -and -not (Test-Path $lockReady);$i++){Start-Sleep -Milliseconds 50};Assert-True (Test-Path $lockReady) 'Lock-holder process did not become ready.';$lockLog=Join-Path $lockRoot 'processor.jsonl';$lockResult=Invoke-HermesProcessor -OneDriveRoot $lockRoot -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $lockRoot 'state.json') -LogPath $lockLog;Assert-Equal $lockResult.items[0].reasonCode 'processor_locked' 'Overlapping run was not classified as processor_locked.';Assert-True ((Format-HermesOutput $lockResult 'Hermes') -ne '[SILENT]') 'Overlapping run was incorrectly suppressed.';Assert-True (Test-Path $lockLog) 'Overlapping-run result was not logged.'}finally{Stop-Job $lockJob -ErrorAction SilentlyContinue;Remove-Job $lockJob -Force -ErrorAction SilentlyContinue}

# Real copied-workbook canary: dry run, one COM batch/save, preserved cells, summary extension, and replay.
$source=$script:SourceWorkbook
$canary=New-TestRoot;$canaryWorkbook=Copy-DisposableWorkbook $canary;$null=Set-WorkbookSentinel $canaryWorkbook;$canaryPayload=New-TestPayload 'eeeeeeee-5555-4555-8555-555555555555' '2026-09-05T12:34:56-07:00' '2026-09-05' '=Example Supermarket' 42.35;$canaryPath=Add-TestHandoff $canary $canaryPayload '20260905_123458';$canaryState=Join-Path $canary 'state.json';$canaryLog=Join-Path $canary 'processor.jsonl';$beforeHash=Get-HermesFileSha256 $canaryWorkbook;$dry=Invoke-HermesProcessor -OneDriveRoot $canary -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath $canaryState -LogPath $canaryLog -DryRun;Assert-Equal $dry.counts.discovered 1 'DryRun discovery count failed.';Assert-Equal $dry.counts.failed 0 'DryRun incorrectly counted an eligible item as failed.';Assert-Equal $dry.items[0].outcome 'eligible' 'DryRun did not report an eligible item.';Assert-True (-not (Test-Path $canaryState)) 'DryRun wrote state.';Assert-Equal (Get-HermesFileSha256 $canaryWorkbook) $beforeHash 'DryRun changed the workbook.'
$write=Invoke-HermesProcessor -OneDriveRoot $canary -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath $canaryState -LogPath $canaryLog;Assert-Equal $write.counts.inserted 1 'COM canary did not insert.';Assert-Equal $write.items[0].reasonCode 'inserted_with_structural_warning' 'Partial transaction rows were not reported with the successful insert.';Assert-True (Test-Path (Join-Path $canary 'Documents/2_Others/Expenses_finance/logs/receipt_jsons_done/expense_20260905_123458_eeeeeeee.json')) 'Canary handoff was not archived.'
$excel=$null;$book=$null;try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$book=$excel.Workbooks.Open($canaryWorkbook,$null,$true);$sheet=$book.Worksheets.Item('2026-09');$summary=$book.Worksheets.Item('Food Expense Summary');$found=@();for($r=12;$r -le 100;$r++){if([string]$sheet.Cells.Item($r,7).Value2 -eq '=Example Mart Sep 05'){$found+=$r}};Assert-Equal $found.Count 1 'Canary inserted row count is not one.';$r=$found[0];Assert-Equal ([decimal]$sheet.Cells.Item($r,6).Value2) ([decimal]42.35) 'Canary F amount is not numeric/correct.';Assert-True (-not [bool]$sheet.Cells.Item($r,7).HasFormula) 'Merchant text beginning with = was interpreted as an Excel formula.';Assert-Equal $sheet.Cells.Item($r,8).Hyperlinks.Item(1).Address 'receipt_images\2026-09\20260905_123456_receipt_eeeeeeee.jpg' 'Canary H hyperlink is not relative.';Assert-Equal ([double]$sheet.Cells.Item($r,5).Value2) ([double]0.5) 'Canary E was not preserved.';Assert-Equal $sheet.Cells.Item($r,16).Value2 'sentinel-unrelated' 'Canary unrelated cell was not preserved.';Assert-True ([string]$sheet.Cells.Item($r,15).Formula -match 'E30|E\d+') 'Canary O formula was not preserved/extended.';Assert-Equal $sheet.Cells.Item($r,6).Style.NameLocal $sheet.Cells.Item(29,6).Style.NameLocal 'Canary row style was not preserved/extended.';Assert-Equal $book.Worksheets.Count 47 'Canary workbook sheet/object count changed.';Assert-Equal $summary.Cells.Item(17,6).Value2 'OK' 'Canary summary coverage failed.';Assert-True ([string]$summary.Cells.Item(1,1).Value2 -match '2026-09') 'Canary summary title was not extended.'}finally{if($book){$book.Close($false);[Runtime.InteropServices.Marshal]::ReleaseComObject($book)|Out-Null};if($excel){$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}

# State replay avoids Excel and retries only the already-completed archive move.
$stateReplay=Join-Path $canary 'Documents/2_Others/Expenses_finance/logs/expense_20260905_123458_eeeeeeee.json';Copy-Item (Join-Path $canary 'Documents/2_Others/Expenses_finance/logs/receipt_jsons_done/expense_20260905_123458_eeeeeeee.json') $stateReplay;$stateReplayRun=Invoke-HermesProcessor -OneDriveRoot $canary -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/missing-workbook.xlsx' -StatePath $canaryState -LogPath (Join-Path $canary 'state-replay.jsonl');Assert-Equal $stateReplayRun.items[0].reasonCode 'already_processed' 'Completed expenseId replay did not bypass the workbook.';Assert-True (-not (Test-Path $stateReplay)) 'Completed expenseId replay did not finish the pending archive move.'

# Workbook-level exact duplicate after state is absent: copy the archived handoff back to inbox with a fresh state.
$replay=Join-Path $canary 'Documents/2_Others/Expenses_finance/logs/expense_20260905_123458_eeeeeeee.json';Copy-Item (Join-Path $canary 'Documents/2_Others/Expenses_finance/logs/receipt_jsons_done/expense_20260905_123458_eeeeeeee.json') $replay;$replayState=Join-Path $canary 'replay-state.json';$replayRun=Invoke-HermesProcessor -OneDriveRoot $canary -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath $replayState -LogPath (Join-Path $canary 'replay.jsonl');Assert-Equal $replayRun.counts.exactDuplicate 1 'Workbook-level exact duplicate was not detected.'

# Multiple files stay in ordinal result order and detect staged exact/similar duplicates within one COM batch.
$batch=New-TestRoot;$batchWorkbook=Copy-DisposableWorkbook $batch;$batchA=New-TestPayload '14141414-1111-4111-8111-111111111111' '2026-09-11T10:00:00-07:00' '2026-09-11' 'Batch Alpha' 8765.43;$batchB=New-TestPayload '15151515-2222-4222-8222-222222222222' '2026-09-11T10:01:00-07:00' '2026-09-11' 'Batch Alpha' 8765.43;$batchC=New-TestPayload '16161616-3333-4333-8333-333333333333' '2026-09-11T10:02:00-07:00' '2026-09-11' 'Batch Beta' 8765.43;$batchPathA=Add-TestHandoff $batch $batchA '20260911_100000';$batchPathB=Add-TestHandoff $batch $batchB '20260911_100100';$batchPathC=Add-TestHandoff $batch $batchC '20260911_100200';$batchRun=Invoke-HermesProcessor -OneDriveRoot $batch -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $batch 'state.json') -LogPath (Join-Path $batch 'processor.jsonl');Assert-Equal $batchRun.counts.inserted 1 'Batch insert count failed.';Assert-Equal $batchRun.counts.exactDuplicate 1 'Staged exact duplicate was not detected.';Assert-Equal $batchRun.counts.review 1 'Staged similar record was not quarantined.';Assert-Equal (($batchRun.items|ForEach-Object fileName) -join ',') ((Split-Path -Leaf $batchPathA)+','+(Split-Path -Leaf $batchPathB)+','+(Split-Path -Leaf $batchPathC)) 'Batch result order was not ordinal.';$batchExact=$batchRun.items|Where-Object outcome -eq 'exact_duplicate'|Select-Object -First 1;Assert-True ($null -ne $batchExact.row -and $batchExact.sheet -eq '2026-09') 'Staged exact duplicate did not report the staged candidate row.';Assert-True (Test-Path (Join-Path $batch 'Documents/2_Others/Expenses_finance/logs/receipt_jsons_review/expense_20260911_100200_16161616.result.json')) 'Staged similar-record review sidecar was not written.'

# Missing-month copy and summary extension on a second disposable copy.
$future=New-TestRoot;$futureWorkbook=Copy-DisposableWorkbook $future;$futureRowsBefore=Get-SummaryUsedRowCount $futureWorkbook;$futurePayload=New-TestPayload 'ffffffff-6666-4666-8666-666666666666' '2026-10-06T12:34:56-07:00' '2026-10-06' 'Future Supermarket' 8.75;$futurePath=Add-TestHandoff $future $futurePayload '20261006_123456';$futureRun=Invoke-HermesProcessor -OneDriveRoot $future -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $future 'state.json') -LogPath (Join-Path $future 'log.jsonl');Assert-Equal $futureRun.counts.inserted 1 'Missing-month canary did not insert.';$excel=$null;$book=$null;try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$book=$excel.Workbooks.Open($futureWorkbook,$null,$true);Assert-True ($null -ne $book.Worksheets.Item('2026-09')) 'Missing month was not copied.';Assert-Equal $book.Worksheets.Item('Food Expense Summary').Cells.Item(17,6).Value2 'OK' 'Missing-month summary coverage failed.';Assert-Equal ([int]$book.Worksheets.Item('Food Expense Summary').UsedRange.Rows.Count) ($futureRowsBefore+90) 'Summary extension copied more than one 89-row detail block.';$futureSummaryModel=Get-HermesSummaryModel $book;Assert-True ([string]::IsNullOrWhiteSpace([string]$book.Worksheets.Item('Food Expense Summary').Cells.Item($futureSummaryModel.DetailEnd+1,1).Value2)) 'Summary extension left copied detail rows beyond the new 89-row block.'}finally{if($book){$book.Close($false);[Runtime.InteropServices.Marshal]::ReleaseComObject($book)|Out-Null};if($excel){$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}

# Missing intermediate months are placed before the earliest later monthly sheet.
$ordering=New-TestRoot;$orderingWorkbook=Copy-DisposableWorkbook $ordering;$excel=$null;$book=$null;try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false;$book=$excel.Workbooks.Open($orderingWorkbook,$null,$false);$book.Worksheets.Item('2026-08').Delete();$created=Ensure-HermesMonthlySheet $book '2026-08';Assert-True ($book.Worksheets.Item('2026-07').Index -lt $created.Index -and $created.Index -lt $book.Worksheets.Item('2026-09').Index) 'Missing monthly sheet was not placed chronologically before the earliest later month.'}finally{if($book){$book.Close($false);[Runtime.InteropServices.Marshal]::ReleaseComObject($book)|Out-Null};if($excel){$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}

# Full transaction capacity defers without saving or moving the valid handoff.
$full=New-TestRoot;$fullWorkbook=Copy-DisposableWorkbook $full;$excel=$null;$book=$null;try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$book=$excel.Workbooks.Open($fullWorkbook,$null,$false);$sheet=$book.Worksheets.Item('2026-09');for($r=12;$r -le 100;$r++){$sheet.Cells.Item($r,6).Value2=[double]$r;$sheet.Cells.Item($r,7).Value2="Occupied $r"};$book.Save()}finally{if($book){$book.Close($false);[Runtime.InteropServices.Marshal]::ReleaseComObject($book)|Out-Null};if($excel){$excel.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()};$fullPayload=New-TestPayload '18181818-5555-4555-8555-555555555555' '2026-09-13T12:00:00-07:00' '2026-09-13' 'Capacity Shop' 12.5;$fullPath=Add-TestHandoff $full $fullPayload '20260913_120000';$fullHash=Get-HermesFileSha256 $fullWorkbook;$fullRun=Invoke-HermesProcessor -OneDriveRoot $full -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $full 'state.json') -LogPath (Join-Path $full 'processor.jsonl');Assert-Equal $fullRun.counts.deferred 1 'Full transaction range did not defer the handoff.';Assert-True (Test-Path $fullPath) 'Full transaction range removed the handoff.';Assert-Equal (Get-HermesFileSha256 $fullWorkbook) $fullHash 'Full transaction range changed the workbook.'

# Existing Excel owner files defer valid handoffs without opening the workbook.
$locked=New-TestRoot;$lockedWorkbook=Copy-DisposableWorkbook $locked;$lockedPayload=New-TestPayload '17171717-4444-4444-8444-444444444444' '2026-09-12T12:00:00-07:00' '2026-09-12' 'Locked Shop' 11.25;$lockedPath=Add-TestHandoff $locked $lockedPayload '20260912_120000';New-Item -ItemType File -Force -Path (Join-Path (Split-Path -Parent $lockedWorkbook) '~$Canada plan.xlsx')|Out-Null;$lockedRun=Invoke-HermesProcessor -OneDriveRoot $locked -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $locked 'state.json') -LogPath (Join-Path $locked 'processor.jsonl');Assert-Equal $lockedRun.counts.deferred 1 'Excel owner lock did not defer the handoff.';Assert-True (Test-Path $lockedPath) 'Excel owner lock removed the handoff from the inbox.'

# Injected pre-save failure leaves the disposable workbook and handoff untouched.
$preSave=New-TestRoot;$preSaveWorkbook=Copy-DisposableWorkbook $preSave;$preSavePayload=New-TestPayload '19191919-6666-4666-8666-666666666666' '2026-09-14T12:00:00-07:00' '2026-09-14' 'Pre Save Shop' 13.5;$preSavePath=Add-TestHandoff $preSave $preSavePayload '20260914_120000';$preSaveHash=Get-HermesFileSha256 $preSaveWorkbook;$preSaveRun=Invoke-HermesProcessor -OneDriveRoot $preSave -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $preSave 'state.json') -LogPath (Join-Path $preSave 'processor.jsonl') -WorkbookUpdater {param($w,$i,$d) throw 'injected_pre_save_failure'};Assert-Equal $preSaveRun.counts.failed 1 'Pre-save failure was not surfaced.';Assert-True (Test-Path $preSavePath) 'Pre-save failure removed the handoff.';Assert-Equal (Get-HermesFileSha256 $preSaveWorkbook) $preSaveHash 'Pre-save failure changed the workbook.'

# Read-only workbook and post-save archive-failure recovery remain conservative and retryable.
$readOnly=New-TestRoot;$readOnlyWorkbook=Copy-DisposableWorkbook $readOnly;$readOnlyPayload=New-TestPayload '12121212-7777-4777-8777-777777777777' '2026-09-07T12:34:56-07:00' '2026-09-07' 'Read Only Shop' 3.25;$readOnlyPath=Add-TestHandoff $readOnly $readOnlyPayload '20260907_123456';(Get-Item -LiteralPath $readOnlyWorkbook).IsReadOnly=$true;try{$readOnlyRun=Invoke-HermesProcessor -OneDriveRoot $readOnly -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $readOnly 'state.json') -LogPath (Join-Path $readOnly 'log.jsonl');Assert-Equal $readOnlyRun.counts.deferred 1 'Read-only workbook was not deferred.';Assert-True (Test-Path $readOnlyPath) 'Read-only workbook lost the handoff.'}finally{(Get-Item -LiteralPath $readOnlyWorkbook).IsReadOnly=$false}
$archiveFailure=New-TestRoot;$archivePayload=New-TestPayload '13131313-8888-4888-8888-888888888888' '2026-09-08T12:34:56-07:00' '2026-09-08' 'Archive Failure Shop' 4.5;$archivePath=Add-TestHandoff $archiveFailure $archivePayload '20260908_123456';$archiveUpdate={param($w,$i,$d) [pscustomobject]@{Saved=$true;Items=@([pscustomobject]@{FileName=(Split-Path -Leaf $archivePath);ExpenseId=$archivePayload.expenseId;Outcome='inserted';ReasonCode='inserted';Message='fake';Sheet='2026-09';Row=12;Candidates=@()})}};$archiveMover={param($s,$d,$complete) throw 'injected_archive_failure'};$archiveRun=Invoke-HermesProcessor -OneDriveRoot $archiveFailure -InboxRelativePath 'Documents/2_Others/Expenses_finance/logs' -WorkbookRelativePath 'Documents/2_Others/Expenses_finance/Canada plan.xlsx' -StatePath (Join-Path $archiveFailure 'state.json') -LogPath (Join-Path $archiveFailure 'log.jsonl') -WorkbookUpdater $archiveUpdate -ArchiveMover $archiveMover;Assert-Equal $archiveRun.counts.failed 1 'Archive failure was not surfaced.';Assert-True (Test-Path $archivePath) 'Archive failure incorrectly removed the handoff.';Assert-True (Test-Path (Join-Path $archiveFailure 'state.json')) 'Post-save state was not persisted before archive failure.'

Assert-Equal (Format-HermesOutput ([pscustomobject]@{counts=[pscustomobject]@{discovered=0}}) 'Hermes') '[SILENT]' 'Quiet Hermes output changed.';$status=Format-HermesOutput $write 'Hermes';Assert-True ($status -match 'inserted=1') 'Hermes output count schema is wrong.';Assert-True ($status -notmatch 'merchantName|42\.35') 'Hermes output leaked payload.'
Remove-Item -LiteralPath $root,$routeRoot,$sidecarFailure,$failureRoot,$lockRoot,$canary,$batch,$future,$ordering,$full,$locked,$preSave,$readOnly,$archiveFailure -Recurse -Force
Write-Host "Hermes Excel unit/integration tests passed: $passed assertions; copied-workbook COM canaries passed."
